export const ProductData = {
    "success": true,
    "data": {
        "totalPageRead": "1",
        "current_count": 7,
        "next": null,
        "prev": null,
        "rows": [
            {
                "_id": "15570",
                "container_id": "B0BZ5QVTTH",
                "shop_id": "290",
                "source_product_id": "B0BZ5FGPBL",
                "type": "simple",
                "user_id": "6465b69eb415b48fe2099134",
                "EAN": "0197347197842",
                "UPC": "197347197842",
                "additional_images": [],
                "app_codes": ["amazonmcf_mirakl"],
                "asin": "B0BZ5FGPBL",
                "brand": "",
                "created_at": "2023-05-05 05:44:47",
                "description": "",
                "language_tag": "en_US",
                "list_price": 0,
                "low_sku": "1bl036bagaz14j",
                "main_image": "",
                "price": 25,
                "quantity": 10,
                "sku": "1BL036BAGAZ14J-new",
                "source_marketplace": "amazonmcf",
                "source_sku": "1BL036BAGAZ14J",
                "title": "Barbie Girls T-Shirts 2-Pack, Malibu Short Sleeve Tees 2-Pack Bundle Set for Girls (Lavender/Pink, Size 4/5)",
                "variant_attributes": [],
                "visibility": "Catalog and Search",
                "weight": "",
                "weight_unit": "",
                "marketplace": [
                    {
                        "shop_id": "290",
                        "source_product_id": "B0BZ5FGPBL",
                        "title": "Barbie Girls T-Shirts 2-Pack, Malibu Short Sleeve Tees 2-Pack Bundle Set for Girls (Lavender/Pink, Size 4/5)",
                        "sku": "1BL036BAGAZ14J",
                        "quantity": 0,
                        "price": 25,
                        "main_image": "",
                        "container_id": "B0BZ5QVTTH",
                        "weight": "",
                        "source_marketplace": "amazonmcf",
                        "direct": true,
                        "additional_images": [],
                        "description": ""
                    },
                    {
                        "shop_id": "212",
                        "source_product_id": "B0BZ5FGPBL",
                        "status": "live",
                        "sku": "1BL036BAGAZ14J-new",
                        "quantity": 9,
                        "price": 25,
                        "container_id": "B0BZ5QVTTH",
                        "target_marketplace": "mirakl"
                    },
                    {
                        "shop_id": "233",
                        "source_product_id": "B0BZ5FGPBL",
                        "status": "live",
                        "sku": "1BL036BAGAZ14J-new",
                        "quantity": 10,
                        "price": 25,
                        "container_id": "B0BZ5QVTTH",
                        "target_marketplace": "mirakl"
                    }
                ],
                "source_status": "live",
                "is_exist": true
            },
            {
                "_id": "18106",
                "container_id": "B0C289FD6Y",
                "shop_id": "290",
                "source_product_id": "JBLCLIP4BLKAM",
                "type": "simple",
                "user_id": "6465b69eb415b48fe2099134",
                "EAN": "0050036378192",
                "UPC": "050036378192",
                "additional_images": [],
                "app_codes": ["amazonmcf_mirakl"],
                "asin": "B08PJ7JMQM",
                "brand": "",
                "created_at": "2023-05-17 09:21:01",
                "description": "",
                "language_tag": "en_US",
                "list_price": 79.95,
                "low_sku": "jblclip4blkam",
                "main_image": "https://m.media-amazon.com/images/I/61nWXk7ZBpL.jpg",
                "price": 69.95,
                "quantity": 1,
                "sku": "JBLCLIP4BLKAM",
                "source_marketplace": "amazonmcf",
                "source_sku": "JBLCLIP4BLKAM",
                "source_status": "error",
                "title": "JBL Clip 4: Portable Speaker with Bluetooth, Built-in Battery, Waterproof and Dustproof Feature - Black (JBLCLIP4BLKAM)",
                "variant_attributes": [],
                "visibility": "Catalog and Search",
                "weight": 0.527,
                "weight_unit": "pounds",
                "marketplace": [
                    {
                        "shop_id": "290",
                        "source_product_id": "JBLCLIP4BLKAM",
                        "title": "JBL Clip 4: Portable Speaker with Bluetooth, Built-in Battery, Waterproof and Dustproof Feature - Black (JBLCLIP4BLKAM)",
                        "sku": "JBLCLIP4BLKAM",
                        "quantity": 1,
                        "price": 69.95,
                        "main_image": "https://m.media-amazon.com/images/I/61nWXk7ZBpL.jpg",
                        "container_id": "B0C289FD6Y",
                        "additional_images": [],
                        "description": "",
                        "weight": 0.527,
                        "source_marketplace": "amazonmcf",
                        "direct": true
                    },
                    {
                        "shop_id": "233",
                        "source_product_id": "JBLCLIP4BLKAM",
                        "status": "pending",
                        "sku": "JBLCLIP4BLKAM",
                        "quantity": 1,
                        "price": 69.95,
                        "container_id": "B0C289FD6Y",
                        "target_marketplace": "mirakl"
                    }
                ]
            },
            {
                "_id": "18110",
                "container_id": "B07X468VBQ",
                "shop_id": "290",
                "source_product_id": "JBLJR300REDAM",
                "type": "simple",
                "user_id": "6465b69eb415b48fe2099134",
                "EAN": "0050036356053",
                "GTIN": "00050036356053",
                "UPC": "050036356053",
                "additional_images": [],
                "app_codes": ["amazonmcf_mirakl"],
                "asin": "B07P577MS7",
                "brand": "",
                "created_at": "2023-05-17 09:21:01",
                "description": "",
                "language_tag": "en_US",
                "list_price": 24.95,
                "low_sku": "jbljr300redam",
                "main_image": "https://m.media-amazon.com/images/I/615EiMBk2KL.jpg",
                "price": 24.95,
                "quantity": 1,
                "sku": "JBLJR300REDAM",
                "source_marketplace": "amazonmcf",
                "source_sku": "JBLJR300REDAM",
                "source_status": "pending",
                "title": "JBL JR 300 - On-Ear Headphones for Kids - Red",
                "variant_attributes": [],
                "visibility": "Catalog and Search",
                "weight": 0.24,
                "weight_unit": "pounds",
                "marketplace": [
                    {
                        "shop_id": "290",
                        "source_product_id": "JBLJR300REDAM",
                        "title": "JBL JR 300 - On-Ear Headphones for Kids - Red",
                        "sku": "JBLJR300REDAM",
                        "quantity": 1,
                        "price": 24.95,
                        "main_image": "https://m.media-amazon.com/images/I/615EiMBk2KL.jpg",
                        "container_id": "B07X468VBQ",
                        "additional_images": [],
                        "description": "",
                        "weight": 0.24,
                        "source_marketplace": "amazonmcf",
                        "direct": true
                    },
                    {
                        "shop_id": "233",
                        "source_product_id": "JBLJR300REDAM",
                        "status": "live",
                        "sku": "JBLJR300REDAM",
                        "quantity": 1,
                        "price": 24.95,
                        "container_id": "B07X468VBQ",
                        "target_marketplace": "mirakl"
                    }
                ]
            },
            {
                "_id": "18111",
                "container_id": "B0BXQ9Y15K",
                "shop_id": "290",
                "source_product_id": "JBLQUANTUM100BLKAM",
                "type": "simple",
                "user_id": "6465b69eb415b48fe2099134",
                "EAN": "0050036369657",
                "UPC": "050036369657",
                "additional_images": [],
                "app_codes": ["amazonmcf_mirakl"],
                "asin": "B084CWCJTW",
                "brand": "",
                "created_at": "2023-05-17 09:21:01",
                "description": "",
                "language_tag": "en_US",
                "list_price": 39.95,
                "low_sku": "jblquantum100blkam",
                "main_image": "https://m.media-amazon.com/images/I/61JNvN9+MZL.jpg",
                "price": 39.95,
                "quantity": 1,
                "sku": "JBLQUANTUM100BLKAM",
                "source_marketplace": "amazonmcf",
                "source_sku": "JBLQUANTUM100BLKAM",
                "source_status": "live",
                "title": "JBL Quantum 100 - Wired Over-Ear Gaming Headphones - Black",
                "variant_attributes": [],
                "visibility": "Catalog and Search",
                "weight": 7.8,
                "weight_unit": "ounces",
                "marketplace": [
                    {
                        "shop_id": "233",
                        "source_product_id": "JBLQUANTUM100BLKAM",
                        "title": "JBL Quantum 100 - Wired Over-Ear Gaming Headphones - Black",
                        "sku": "JBLQUANTUM100BLKAM",
                        "quantity": 1,
                        "price": 39.95,
                        "main_image": "https://m.media-amazon.com/images/I/61JNvN9+MZL.jpg",
                        "container_id": "B0BXQ9Y15K",
                        "additional_images": [],
                        "description": "",
                        "weight": 7.8,
                        "status": "error",
                        "source_marketplace": "amazonmcf",
                        "direct": true
                    },
                    {
                        "shop_id": "649",
                        "source_product_id": "JBLQUANTUM100BLKAM",
                        "status": "live",
                        "sku": "JBLQUANTUM100BLKAM",
                        "quantity": 1,
                        "price": 39.95,
                        "container_id": "B0BXQ9Y15K",
                        "target_marketplace": "mirakl"
                    }
                ]
            },
            {
                "_id": "18114",
                "container_id": "B08GR4D4BM",
                "shop_id": "290",
                "source_product_id": "JBLQUANTUM50BLKAM",
                "type": "simple",
                "user_id": "6465b69eb415b48fe2099134",
                "EAN": "0050036373838",
                "UPC": "050036373838",
                "additional_images": [],
                "app_codes": ["amazonmcf_mirakl"],
                "asin": "B08D7WQ6NM",
                "brand": "",
                "created_at": "2023-05-17 09:21:01",
                "description": "",
                "language_tag": "en_US",
                "list_price": 29.95,
                "low_sku": "jblquantum50blkam",
                "main_image": "https://m.media-amazon.com/images/I/51jtnXD8BlL.jpg",
                "price": 29.95,
                "quantity": 4,
                "sku": "JBLQUANTUM50BLKAM",
                "source_marketplace": "amazonmcf",
                "source_sku": "JBLQUANTUM50BLKAM",
                "source_status": "live",
                "title": "JBL Quantum 50 Wired, in-Ear Gaming Headphones with Inline Control - Black",
                "variant_attributes": [],
                "visibility": "Catalog and Search",
                "weight": 21.5,
                "weight_unit": "grams",
                "marketplace": [
                    {
                        "shop_id": "290",
                        "source_product_id": "JBLQUANTUM50BLKAM",
                        "title": "JBL Quantum 50 Wired, in-Ear Gaming Headphones with Inline Control - Black",
                        "sku": "JBLQUANTUM50BLKAM",
                        "quantity": 4,
                        "price": 29.95,
                        "main_image": "https://m.media-amazon.com/images/I/51jtnXD8BlL.jpg",
                        "container_id": "B08GR4D4BM",
                        "additional_images": [],
                        "description": "",
                        "weight": 21.5,
                        "source_marketplace": "amazonmcf",
                        "direct": true
                    },
                    {
                        "shop_id": "233",
                        "source_product_id": "JBLQUANTUM50BLKAM",
                        "status": "live",
                        "sku": "JBLQUANTUM50BLKAM",
                        "quantity": 4,
                        "price": 29.95,
                        "container_id": "B08GR4D4BM",
                        "target_marketplace": "mirakl"
                    }
                ]
            },
            {
                "_id": "18115",
                "container_id": "B08GR4D4BM",
                "shop_id": "290",
                "source_product_id": "JBLQUANTUM50WHTAM",
                "type": "simple",
                "user_id": "6465b69eb415b48fe2099134",
                "EAN": "0050036373845",
                "UPC": "050036373845",
                "additional_images": [],
                "app_codes": ["amazonmcf_mirakl"],
                "asin": "B08D7Y5HN3",
                "brand": "",
                "created_at": "2023-05-17 09:21:01",
                "description": "",
                "language_tag": "en_US",
                "list_price": 29.95,
                "low_sku": "jblquantum50whtam",
                "main_image": "https://m.media-amazon.com/images/I/515fbPpBjjL.jpg",
                "price": 29.95,
                "quantity": 1,
                "sku": "JBLQUANTUM50WHTAM",
                "source_marketplace": "amazonmcf",
                "source_sku": "JBLQUANTUM50WHTAM",
                "source_status": "not_upload",
                "title": "JBL Quantum 50 Wired, in-Ear Gaming Headphones with Inline Control - White",
                "variant_attributes": [],
                "visibility": "Catalog and Search",
                "weight": 21.5,
                "weight_unit": "grams",
                "marketplace": [
                    {
                        "shop_id": "290",
                        "source_product_id": "JBLQUANTUM50WHTAM",
                        "title": "JBL Quantum 50 Wired, in-Ear Gaming Headphones with Inline Control - White",
                        "sku": "JBLQUANTUM50WHTAM",
                        "quantity": 1,
                        "price": 29.95,
                        "main_image": "https://m.media-amazon.com/images/I/515fbPpBjjL.jpg",
                        "container_id": "B08GR4D4BM",
                        "additional_images": [],
                        "description": "",
                        "weight": 21.5,
                        "source_marketplace": "amazonmcf",
                        "direct": true
                    },
                    {
                        "shop_id": "233",
                        "source_product_id": "JBLQUANTUM50WHTAM",
                        "status": "live",
                        "sku": "JBLQUANTUM50WHTAM",
                        "quantity": 1,
                        "price": 29.95,
                        "container_id": "B08GR4D4BM",
                        "target_marketplace": "mirakl"
                    }
                ]
            },
            {
                "_id": "18116",
                "container_id": "B08M5D5SHH",
                "shop_id": "290",
                "source_product_id": "JBLT205BTBLKAM",
                "type": "simple",
                "user_id": "6465b69eb415b48fe2099134",
                "EAN": "0050036358620",
                "UPC": "050036358620",
                "additional_images": [],
                "app_codes": ["amazonmcf_mirakl"],
                "asin": "B07PHVQFJK",
                "brand": "",
                "created_at": "2023-05-17 09:21:01",
                "description": "",
                "language_tag": "en_US",
                "list_price": 39.95,
                "low_sku": "jblt205btblkam",
                "main_image": "https://m.media-amazon.com/images/I/61AFrFey7-L.jpg",
                "price": 39.95,
                "quantity": 4,
                "sku": "JBLT205BTBLKAM",
                "source_marketplace": "amazonmcf",
                "source_sku": "JBLT205BTBLKAM",
                "source_status": "live",
                "title": "JBL TUNE 205BT - In-Ear Wireless Bluetooth Headphone - Black",
                "variant_attributes": [],
                "visibility": "Catalog and Search",
                "weight": 16.5,
                "weight_unit": "grams",
                "marketplace": [
                    {
                        "shop_id": "290",
                        "source_product_id": "JBLT205BTBLKAM",
                        "title": "JBL TUNE 205BT - In-Ear Wireless Bluetooth Headphone - Black",
                        "sku": "JBLT205BTBLKAM",
                        "quantity": 4,
                        "price": 39.95,
                        "main_image": "https://m.media-amazon.com/images/I/61AFrFey7-L.jpg",
                        "container_id": "B08M5D5SHH",
                        "additional_images": [],
                        "description": "",
                        "weight": 16.5,
                        "source_marketplace": "amazonmcf",
                        "direct": true
                    },
                    {
                        "shop_id": "233",
                        "source_product_id": "JBLT205BTBLKAM",
                        "status": "live",
                        "sku": "JBLT205BTBLKAM",
                        "quantity": 4,
                        "price": 39.95,
                        "container_id": "B08M5D5SHH",
                        "target_marketplace": "mirakl"
                    }
                ]
            }
        ]
    },
    "start_time": "05-23-2023 11:27:01",
    "end_time": "05-23-2023 11:27:01",
    "execution_time": 0.021284103393554688,
    "ip": "127.0.0.1",
    "time_taken": "0.037"
}